<a href="https://colab.research.google.com/github/Rogerio-mack/ABCXYZ/blob/main/Oriba_just_head_print.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="Universidade Presbiteriana Mackenzie">
</head>

<img src="http://meusite.mackenzie.br/rogerio/mackenzie_logo/UPM.2_horizontal_vermelho.jpg" width=300, align="right"> 
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->

<br>
<br>
<br>
<br>
<br>

# head print
---

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df = pd.read_csv('https://github.com/Rogerio-mack/ABCXYZ/raw/main/oriba_base_reshaped.csv',index_col=0)
df.index = pd.to_datetime(df.index)
df = df.dropna(axis=1) 

pd.set_option('display.max_colwidth', -1)
pd.set_option('display.max_rows', 8)

df.columns = [x.split(' ')[0] + ' ' + x.split(' ')[1] + '...' for x in df.columns]
df = df.loc[:, ~df.columns.duplicated()]
display( df[ df.columns[0:8] ] )

            Bermuda Chino...  Bermuda Moletom...  Blusa Moletom...  Calça Chino...  Camisa Flanela...  Camisa Jeans...  Camisa Pima...  Camiseta Essencial...
2018-01-31  9.0               4.0                 1.0               12.0            6.0                17.0             7.0             16.0
2018-02-28  4.0               2.0                 3.0               9.0             5.0                12.0             7.0             12.0
2018-03-31  8.0               3.0                 0.0               16.0            3.0                16.0             5.0             26.0
2018-04-30  2.0               0.0                 5.0               13.0            4.0                10.0             17.0            20.0
...         ...               ...                 ...                ...            ...                 ...              ...             ...
2021-09-30  21.0              3.0                 0.0               25.0            0.0                12.0             6.0             35.0
2021-10-31  15.0              2.0                 0.0               17.0            0.0                16.0             3.0             0.0
2021-11-30  10.0              0.0                 0.0               54.0            0.0                10.0             6.0             0.0
2021-12-31  13.0              0.0                 0.0               39.0            0.0                2.0              1.0             0.0

[48 rows x 8 columns]